# Generated by Django 5.2.1 on 2025-06-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('regid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('confirmpassword', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=500)),
                ('course', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('status', models.IntegerField()),
                ('role', models.CharField(max_length=30)),
                ('info', models.CharField(max_length=30)),
                ('verification_token', models.CharField(blank=True, max_length=32, null=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
