# Generated by Django 5.2.1 on 2025-06-22 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommarce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='confirmpassword',
        ),
    ]
