# Generated by Django 5.2.1 on 2025-06-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommarce', '0002_remove_register_confirmpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='dbo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
