# Generated by Django 5.2.1 on 2025-06-22 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommarce', '0003_register_dbo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='dbo',
            new_name='dob',
        ),
    ]
